{"implements":[],"javadoc":"<code>AssertException<\/code> is used in situations that the programmer believes can't happen.\n If it does, then there is a programming error of some kind.","static":false,"extends":"java.lang.RuntimeException","methods":[{"javadoc":"Create a new AssertException with no message.","static":false,"name":"<init>","comment":"Create a new AssertException with no message.","params":[],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}},{"javadoc":"Create a new AssertException with the given message.\n@param msg the exception message.","static":false,"name":"<init>","comment":"Create a new AssertException with the given message.","params":[{"type_long":"java.lang.String","name":"msg","comment":"the exception message.","type_short":"String"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}},{"javadoc":"Create a new AssertException using another exception (Throwable) has occurred.\n The message for this exception will be derived from the Throwable.\n@param t the Throwable which caused this exception to be generated.","static":false,"name":"<init>","comment":"Create a new AssertException using another exception (Throwable) has occurred.\n The message for this exception will be derived from the Throwable.","params":[{"type_long":"java.lang.Throwable","name":"t","comment":"the Throwable which caused this exception to be generated.","type_short":"Throwable"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}},{"javadoc":"Create a new AssertException with the given message.\n@param msg the exception message.\n@param t the Throwable which caused this exception to be generated.","static":false,"name":"<init>","comment":"Create a new AssertException with the given message.","params":[{"type_long":"java.lang.String","name":"message","comment":"","type_short":"String"},{"type_long":"java.lang.Throwable","name":"throwable","comment":"","type_short":"Throwable"}],"throws":[],"return":{"type_long":"void","comment":"","type_short":"void"}}],"name":"AssertException","comment":"AssertException is used in situations that the programmer believes can't happen.\n If it does, then there is a programming error of some kind.","fields":[]}
